"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layouts/navbar";
import { usePathname } from "next/navigation";
import { SessionProvider } from "next-auth/react";
import Footer from "@/components/layouts/Footer";

const inter = Inter({ subsets: ["latin"] });

const disableNavbar = ["/login", "/register", "/dashboard"];

const disableNavbarChildren = [
  "/dashboard/blog",
  "/dashboard/settings",
  "/dashboard/messages",
];

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  const isNavbarDisabled =
    disableNavbar.includes(pathname) ||
    disableNavbarChildren.includes(pathname) ||
    pathname.startsWith("/dashboard/");

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          {!isNavbarDisabled && <Navbar />}
          {children}
          {<Footer />}
        </SessionProvider>
      </body>
    </html>
  );
}
